### ISSUE TITLE
Decrease ipfs-js size

### ISSUE THREAD

**Issue by dholms** [fission-suite/drive#1]
Right now `ipfs.js` is 5.6MB. `get-ipfs` isn't much better (2.22MB since we're getting the minified version).

After talking with Hugo at Diffusion, the vast majority of that is different IPLD formats, nearly all of which we aren't using. 

I believe [ipfs-provider](https://github.com/ipfs-shipyard/ipfs-provider) is more flexible in regards to which IPLD formats you import. 

I mostly wanted to flag this since at some point we'll want to do one of the following:
- make a custom smaller `ipfs.js`
- update `get-ipfs` to be flexible around IPLD formats
- fork `ipfs-provider`, add features that we need (such as es6 syntax)

**Comment by icidasset** [comment]
Superseded by #105 
The heavier part (js-ipfs) lives on the auth lobby and the apps (ie. webnative) use a lightweight client.
Since we created this issue js-ipfs has gotten smaller too by including less IPLD formats.
