### ISSUE TITLE
Code Structure: Change Elm/Webnative communication

### ISSUE THREAD

**Issue by matheus23** [fission-suite/drive#101]
(*movie trailer voice*) Previously, in #94:

> > This requires some coordination from Elm -> Ports -> Webnative -> Ports -> Elm
>
> Yeah that's not that easy, for sure. I was thinking of doing this https://discourse.elm-lang.org/t/service-worker-ffi/6408 pattern, so we can use Tasks for our webnative interactions (and thus chain filesystem actions). But then we're depending on service workers for the most crucial parts of the system... which is probably not a good idea? :thinking:

Yeah, I've tried to do that before, but I don't recommend it, unless there exists an actual REST endpoint which you replicate in a service worker. I've heard that on iOS service workers often don't run and in general they can't be relied upon to be running, so I wouldn't consider them for an integral part of the app.
Man, Tasks for ports in elm would be nice, huh.

> > From looking at the code it seems to me like when I quickly remove lots of files, as soon as model.fileSystemStatus goes to Ready once, they all should disappear, but that's not the case.
> 
> It's not that advanced no. The condition is just for adding the notification on that exact moment. Which in some cases doesn't even make sense, because it's always going to be true. That library I used doesn't have that much features, can't even remove a notification, so we should probably look for something better.

So... Just for clarity, the notifications just disappear after a set amount time?

> > I have some ideas on how to do this Elm -> Webnative -> Elm communication
> 
> Shoot :gun:

Okay, here's the plan:

We basically want something Task-like for webnative calls. We want to connect file system calls and their responses.

Unfortunately, we can't simply do this:
```elm
-- in Ports.elm
port fsWriteItemUtf8 :
    { pathSegments : List String
    , text : String

    -- Provide an function that specifies what to do after this call succeeded.
    , followup : GotDirectoryListResultStuff -> Model -> ( Model, Cmd Msg )
    }
    -> Cmd msg
```

As we can't serialize function calls.

So let's do the elm architecture thing and use serializable messages instead:

```elm
-- somewhere else

import Codec -- from miniBill/elm-codec

type FollowupMsg
    = PlaintextEditorSavingFinished
    | -- ...

codecFollowupMessage : Codec FollowupMsg
-- ...


-- in Ports.elm

port fsWriteItemUtf8 :
    { pathSegments : List String
    , text : String

    -- Provide the json value that was encoded from the followupMsg
    , followupMsg : Json.Encode.Value
    }
    -> Cmd msg


-- somewhere else again

updateFollowup : GotDirectoryListResultStuff -> FollowupMsg -> Model -> ( Model, Cmd Msg )
-- ... here the 
```

The idea is that `updateFollowup` will be called when the file system call gets back to elm. This will happen through `gotDirectoryList`. The value `followupMsg` which was provided in `fsWriteItemutf8` will be passed through in the javascript code back to `gotDirectoryList` without touching it, where it gets decoded again and `gotDirectoryList` will call `updateFollowup`.

So to summarize:
* Elm calls e.g. `fsWriteItemUtf8`, provides a `FollowupMsg`, encoded as a Json.Encode.Value
* Javascript awaits the WNFS call. After it finishes, it calls the port `gotDirectoryList` to elm, providing the `followupMsg : Json.Encode.Value`
* `gotDirectoryList` decodes the `followupMsg : Json.Encode.Value` into an actual `FollowupMsg` again
* and runs `updateFollowup` with whatever extra data it's got from Javascript (`GotDirectoryListResultStuff`, obviously a temporary name)

I hope this isn't too confusing. I'd PR this soon, as I think it's a useful core design: We'll likely need to answer some specific file system calls once they've completed in the future.

I guess I'm waiting for a 'go' on this one, if you think it's worthwhile @icidasset . In any case, you can message me on discord and we can have a call, too, I feel like in some cases that's faster.

**Comment by icidasset** [comment]
> So... Just for clarity, the notifications just disappear after a set amount time?

Yessir.

> let's do the elm architecture thing and use serializable messages instead:

Seems like the right direction, good stuff 👍 
I think we can make an abstraction for this, so we don't need to add `followUpMsg` to every port 🤔 

Perhaps something like:
```elm
type ExternalAction
  = Filesystem { pathSegments : List String } FilesystemAction

type FilesystemAction
  = WriteItemUtf8 { text : String }


externalActionCodec : Codec ExternalAction


port externalize :
  { externalAction : Json.Encode.Value
  , followUpMsg : Json.Encode.Value
  }
  -> Cmd msg

port externalized :
  (
    { actionResults : Json.Encode.Value
    , followUpMsg : Json.Encode.Value
    }
    -> msg
  )
  -> Sub msg
```
And then the action results would be passed to the follow up message, either by passing the json value, or by setting up some kind of decoder system.

Not entirely sure about this interface, need to think a bit more about this.
That said, there are some existing solutions we can use, such as: https://package.elm-lang.org/packages/peterszerzo/elm-porter/latest/

What do you think?

**Comment by matheus23** [comment]
>  I think we can make an abstraction for this, so we don't need to add followUpMsg to every port :thinking:
> What do you think?

~~I wouldn't mind going without an abstraction for now, the overhead of adding followupMsg everywhere seems fine~~

> That said, there are some existing solutions we can use, such as: https://package.elm-lang.org/packages/peterszerzo/elm-porter/latest/

Wow. :star_struck: I was not aware. This looks perfect and seems to have already evolved a little (to me this means the abstractions are likely better that what I'd have come up with).

As far as I know it also provides exactly what we need. I'd be happy to just go ahead and build upon elm-porter. :tada:

---

I have to think a little about how to do this incrementally the best way, though.

I guess the first step would be making gotDirectoryList the response for all file system requests for now.
The next step would be splitting up gotDirectoryList to have more specific responses for the individual requests (saving in the plaintext editor, navigating through directories, etc.).

I think I have a plan of how to do this.

**Comment by matheus23** [comment]
So, I've taken another look at elm-porter.
One downside would be that [there will be functions stored in the model](https://github.com/peterszerzo/elm-porter/blob/1d079c16b6f0063fde21aee34c46d6f2da05535b/src/Porter.elm#L45-L51) (you need to follow the type rabbit hole to see the functions).
[This is discouraged](https://github.com/evancz/elm-sortable-table#usage-rules). The consequences of this seem to be:
1. The debugger import/export won't work
2. Hot reloading might not work
3. Html.lazy won't work (However, I see this as a non-issue, as I wouldn't expect the view to depend on the elm-porter model)

I haven't tested points (1) and (2). It makes a lot of sense that the debugger import/export breaks, but I'm not too sure about (2) and haven't tested it yet.

My proposed solution above wouldn't have this issue (but be a little more overhead compared to elm-porter).
Current gut feeling: Let's run with a custom solution and keep the elm-porter API in the back of our heads for guidance in terms of possible API evolution.

**Comment by icidasset** [comment]
> I have to think a little about how to do this incrementally the best way, though.

Let's write the abstraction layer, something similar to what I suggested. I definitely like the `Codec` setup you suggested, hopefully that'll work smoothly with custom types (as in my example). And then switch out the existing ports one by one.

So for example, replace:
```elm
-- Outgoing
Ports.fsCreateDirectory { pathSegments = segments }

-- Incoming
subscriptions = Ports.fsGotDirectoryList.subscribe(GotDirectoryListOld) -- Temporary Msg to handle old code
```
with
```elm
-- Outgoing
Externalize.cmd
  [ ("pathSegments", Encode.list Encode.string segments) ]
  (GotDirectoryList segments)

-- Incoming
subscriptions = Ports.externalized GotExternalizationResult

gotExternalizationResult = Externalize.handleResult -- Which eventually calls the following 👇
gotDirectoryList : List String -> Json.Value -> Manager
```

Does that make sense?

> I guess the first step would be making gotDirectoryList the response for all file system requests for now.

I wouldn't do that. Lets focus on our original goal, the ability to chain commands/ports. Once we have the abstraction we can gradually apply it, and make new `Msg`s where needed.

**Comment by icidasset** [comment]
Superseded by https://github.com/fission-suite/webnative-elm
We'll refactor Drive to use that library.

See `GotWnfsResponse` in the example how to chain WNFS actions, and how to handle data coming from the filesystem.
