### ISSUE TITLE
Clickable elements invisible to accessibility tools

### ISSUE THREAD

**Issue by agentofuser** [fission-suite/drive#112]
Small but important feedback on the Drive UI: I rely heavily on Vimium for keyboard accessibility, and on drive.fission.codes when I press 'f' to highlight clickable elements it says "No links to select." I think they are all clickable divs/spans at the moment. Would it be possible to make them <a></a> elements or button or some other thing Vimium recognizes? It will probably also help people using screen readers and stuff.

I'll be happy to help test this or provide more information. Thanks!

**Comment by expede** [comment]
[Chiming in several months later] I am a pretty heavy vim-vixen user (a similar extension), and have been using a ouse for Drive. Thanks for mentioning it @agentofuser 👍 Certainly a quality of life thing

**Comment by icidasset** [comment]
Clickable elements that change the current directory are now `<a>` links and files are `<button>`s. This also adds the benefit that links can be opened easily in a new tab or window.

Live on staging, not production yet: https://drive.runfission.net
