### ISSUE TITLE
Image preview doesn't work if the file extension is in caps.

### ISSUE THREAD

**Issue by therealjeffg** [fission-suite/drive#132]
# Summary

Image files in drive with all caps file extensions don't preview when clicked on.

**To Reproduce**
1. add this file to your public drive folder:

https://ipfs.runfission.com/ipfs/bafybeih7rj6k4xiv2ppzqvc6w6vi6uly4duwqbqaeyokfnywdo2lcdogfu/p/img/lambda.PNG

2. go to the directory where it is located and click on 'lambda'. The image will briefly appear and then disappear.

Other images remain visible. Using drive's "re-name" feature to rename the file 'lambda.png' fixes the issue.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser Firefox
 - Version 89

Another thing, perhaps relevant - the .PNG file never gets the image icon:

![Screenshot 2021-05-26 at 15-14-49 Fission Drive - Your Web Native File System](https://user-images.githubusercontent.com/104315/119738268-4aa7ff00-be35-11eb-839b-d8a3ec3357dd.png)

**Comment by therealjeffg** [comment]
After a bit of poking around, it looks like this check is case sensitive, eg all CAPS file extensions would fail to be identified.

https://github.com/fission-suite/drive/blob/c3d7e17d76f302b122112628f9ca370fc9352536/src/Application/Drive/Item.elm#L137

**Comment by icidasset** [comment]
@therealjeffg Thanks! Should be fixed now 👀

**Comment by therealjeffg** [comment]
Confirmed!
