### ISSUE TITLE
Browsing public Drive folders in Incognito / private browsing mode doesn't work

### ISSUE THREAD

**Issue by bmann** [fission-suite/drive#133]
If you send someone a public drive link link https://drive.fission.codes/#boris/public/PDFs/, and the other person is in an Incognito window, Drive never loads.

No errors in console. Tested in both Safari iOS "private" mode and MacOS Chrome desktop "incognito"

**Comment by expede** [comment]
I would love to find a way around this 💯 

Different browsers have different APIs disabled. For example, from [MDN](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB):

> IndexedDB storage in browsers' privacy modes only lasts in-memory until the incognito session is closed (Private Browsing mode for Firefox and Incognito mode for Chrome, but in Firefox this is not implemented yet as of May 2021 so you can't use IndexedDB in Firefox Private Browsing at all).

**Comment by expede** [comment]
For this app in particular, we could fall back to HTTP rather than depending on native js-ipfs loading 🤔

**Comment by matheus23** [comment]
That would be an option. It's also very easy to configure js-ipfs to store their blocks in memory:

https://github.com/fission-suite/webnative/blob/ef3f1c997b9440025d84aadfe3f73a964578c28e/tests/helpers/in-memory-ipfs.ts#L14-L27

If we can detect IDB support and switch to an in-memory store with a console warning, I think that'd be good :+1:

**Comment by bmann** [comment]
Just replicated on Desktop Safari, not in Private mode, by trying to go to `drive.fission.codes/#boris`. Which, um, is an incorrect path :) `https://drive.fission.codes/#/boris/` doesn't load, but if you go to a subfolder like PDFs, then you can go back and the public root will load.

Going to `drive.fission.codes/#boris/PDFs` works and the whole thing is then browseable.

@therealjeffg reported same issue in Firefox on MacOS.

@matheus23 reported it DID work on Firefox on Linux.

The console messages I see are all `worker.min.js` -- no errors, just logging

**Comment by therealjeffg** [comment]
I got an error from debugging the shared worker but it isn't very helpful:

<img width="315" alt="Screen Shot 2021-06-04 at 11 54 08 AM" src="https://user-images.githubusercontent.com/104315/120849998-b3753280-c52b-11eb-9a2e-1d564c1a4977.png">

**Comment by therealjeffg** [comment]
I think an initial goal here is to catch any errors from the worker in a way that pipes them into the page's console so that errors are surfaced int the page that is using the worker ( when applicable )

**Comment by icidasset** [comment]
This issue consists out of a few different problems.

1. The public folder loading doesn't work, on any browser (unless you change the path after loading the app)
2. We don't show the error message that the browser is not supported, which is current only "private mode" in Firefox.

Fix:
1. Actually load the public filesystem (this wasn't the case any longer after recent updates)
2. Show error messages when needed

I won't try to find a way around indexeddb for private firefox, doesn't seem worth the effort. And there's a way around this, by setting `dom.indexedDB.privateBrowsing.enabled` to true in the Firefox settings.

**Comment by icidasset** [comment]
Both issues mentioned above should be fixed.

https://drive.fission.codes/#/boris now loads fine for me on:
- macOS 11.1 Safari, Firefox (Stable), Chrome (Stable)
- iOS 14.6 Firefox & Safari

**Comment by icidasset** [comment]
I've tested it again and seems to work, please reopen if it doesn't work for you.
