### ISSUE TITLE
auth help is 404

### ISSUE THREAD

**Issue by jean** [fission-suite/drive#135]
# Summary

Following the "learn more" link from Drive signup results in a 404:

![Screenshot_20210613-115230_Firefox](https://user-images.githubusercontent.com/84800/121795830-76512480-cc3e-11eb-8d41-80066a9b06fa.jpg)

## Problem

Describe the immediate problem

### Impact

The impact that this bug has

## Solution

Describe the sort of fix that would solve the issue

# Detail

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bmann** [comment]
@jean thanks for the report! I'm guessing we shuffled stuff around in the Guide and didn't use a more perma-link on the learn more side. 

I've fixed this for now, this is the "learn more" from giving app permissions.

<img width="896" alt="Screen Shot 2021-06-12 at 10 08 01 PM" src="https://user-images.githubusercontent.com/280420/121796082-3bfa6f80-cbcb-11eb-9f1e-bdc65a621824.png">

@bgins @icidasset no easy way to track this, but we do have to be aware of changing pages can change the "slug" of pages.
