### ISSUE TITLE
apps and cli links broken in welcome message

### ISSUE THREAD

**Issue by olizilla** [fission-suite/drive#145]
Links to "various apps" and "Fission CLI" are broken in the new user welcome message box

<img width="1245" alt="Screenshot 2021-09-22 at 10 07 34" src="https://user-images.githubusercontent.com/58871/134316124-d1449aae-4e64-47aa-a461-d561802a89f0.png">

https://fission.codes/apps -> `ipfs resolve -r /ipns/fission.codes/apps: no link named "apps" under bafybeihyzje53vweip5msvj3nxkjvyjnwvurrg5vcek2is3c7a2plxgjze`

https://guide.fission.codes/hosting/installation -> 404

related #135

**Comment by bmann** [comment]
Thanks @olizilla — we shifted some things around, will get those fixed up. That’s in the Drive app.

**Comment by olizilla** [comment]
no worries! i flag this in solidarity!

**Comment by bmann** [comment]
@olizilla apps list is live! https://fission.codes/apps/

Broken guide link should be fixed by morning, thanks again for reporting
