### ISSUE TITLE
Implement service worker support for IPFS

### ISSUE THREAD

**Issue by bmann** [fission-suite/drive#34]
I'll start with the big part. IPFS Companion is a browser extension. Extensions run in the main web UI thread. Service / web workers run in their own thread.

To improve performance of Drive, we could implement a service worker version of IPFS running in the browser.

This would not be compatible with IPFS Companion, so this means dropping support for IPFS Companion. It has about 20K installs and lets users run a local IPFS node.

Since we focus on making our services work web native in all browsers, even if they use some cutting edge tech, relying on extensions isn't in line with our goals.

The problem is that we need a separate ipfs daemon in every webpage. So, performance when running multiple apps / across multiple domains may be an issue.

Relevant discussions from IPFS land:
* https://github.com/ipfs/in-web-browsers/issues/137
* https://github.com/ipfs-shipyard/service-worker-gateway
* Progressive P2P Web Apps (PPWA) https://gozala.hashbase.io/posts/Native%20talk.html

**Comment by icidasset** [comment]
Superseded by #105
