### ISSUE TITLE
crypto.subtle.importKey fails on redirect after granting permissions with fission auth

### ISSUE THREAD

**Issue by matheus23** [fission-suite/drive#71]
# Summary

I'm running the development server with `just`. I'm working in a direnv with the shell.nix.
* I go to `localhost:8000`, click "sign in with fission" -> I get linked to either `auth.fission.codes` or `round-aquamarine-dinosaur.fission.app`, depending on whether I run production or not
* I grant permissions by clicking "Yes" -> I get redirected to `localhost:8000`

## Problem

I only see a white screen, nothing loads.
There's an exception in the console:
In firefox: `DOMException: Data provided to an operation does not meet requirements`
In chrome: `DOMException: AES key data must be 128 or 256 bits`

Also, the spinner can't load, because it tries to work with the html element with id `"elm"`, but there is none, as the javascript code failed before it could `.init` the elm app.

### Impact

I can't check out fission drive. I'm sad :frowning_face: 

# Detail

I'm running this in both firefox version 80.0.1 and chrome version 85.0.4183.83 on ArchLinux.

The call that's failing seems to be this one:
https://github.com/fission-suite/keystore-idb/blob/678d78d10071c5012f4c3e8a8790a46c9293d342/src/aes/keys.ts#L18-L27
Further up the call stack we seem to be here:
https://github.com/fission-suite/keystore-idb/blob/678d78d10071c5012f4c3e8a8790a46c9293d342/src/keystore/base.ts#L54
Anything else seems to be hard to trace back.

**Comment by icidasset** [comment]
Thanks for the bug report 🙏 

I've updated the SDK which should fix this issue.
Be sure to clear all your local data before you try again.

Staging/dev lobby is now located at `auth.runfission.net` (instead of "round dinosaur").
I also made a build of Drive that points at the staging lobby, at https://drive.runfission.net

**Comment by matheus23** [comment]
Thanks! This issue is resolved :)
