### ISSUE TITLE
Opening drive without a fragment when authenticated results in indefinite loading screen.

### ISSUE THREAD

**Issue by matheus23** [fission-suite/drive#72]
Opening `localhost:8000` when having already authenticated once leads to an indefinite spinner for me, assuming fission drive runs on port 8000.

Following situations work:
* Opening `localhost:8000/#/matheus23-drive` when already authenticated
* Opening `localhost:8000` without being authenticated, getting redirected to `auth.runfission.net` and back.

I tested all of this with `drive.runfission.net`, too, and it seems to have exactly the same issues.

In the last situation, when getting redirected back from `auth.runfission.net`, it seems like for some reason the app adds the `/matheus23-drive` url fragment.
Not sure why that's not happening when I'm already logged in.

**Comment by matheus23** [comment]
It seems like this should be the place where the url fragment would be set:
https://github.com/fission-suite/drive/blob/a3a8f9f0c73cb7776d61fe7b5d978b4d527cb697/src/Application/Ipfs/State.elm#L103-L107

However, that code is never run in the failing case.
It seems like it should be triggered by javascript:
https://github.com/fission-suite/drive/blob/a3a8f9f0c73cb7776d61fe7b5d978b4d527cb697/src/Application/State.elm#L303

This port in turn is triggered by an elm outgoing port:
https://github.com/fission-suite/drive/blob/a3a8f9f0c73cb7776d61fe7b5d978b4d527cb697/src/Javascript/index.js#L101

And that port should probably be triggered by one of these two cases (In Ipfs.State, again):
https://github.com/fission-suite/drive/blob/a3a8f9f0c73cb7776d61fe7b5d978b4d527cb697/src/Application/Ipfs/State.elm#L53-L70

**Comment by matheus23** [comment]
Okay, I've just inserted some code to the first case in `setupCompleted` to change the url fragment, similar to how it's done in `gotResolvedAddress`.

This fixes the issue for me. I'll open a PR. Not sure if this is the 'correct' fix, though.

**Comment by icidasset** [comment]
Thanks @matheus23 ! Glad you were able to fix it 🎉 
I should really go through the code one of these days and clean it up.
