### ISSUE TITLE
Touch events not registered

### ISSUE THREAD

**Issue by expede** [fission-suite/drive#74]
# Summary

## Problem

Touch events do not work

### Impact

Precludes use on phones and tablets when not using a mouse

## Solution

Describe the sort of fix that would solve the issue

# Detail

**Describe the bug**

**To Reproduce**
1. Go to magenta-knight.fission.app
2. Load a file system
3. Attempt to tap on items
4. Nothing happens
5. Click with mouse
6. Expected behaviour occurs

**Expected behavior**
Tap behaves like a click

**Smartphone (please complete the following information):**
 - Device: iPad Pro 11”
 - OS: iPadOS 14.0
 - Browser: Safari
 - Version: Unclear. 14?

**Comment by matheus23** [comment]
This should be fixed by #77. Can you confirm, @expede? :)

**Comment by bmann** [comment]
thanks for deploying https://drive.fission.net — touch events work, thanks!
