### ISSUE TITLE
Disable directory tree on single-file views

### ISSUE THREAD

**Issue by icidasset** [fission-suite/drive#78]
<img width="1045" alt="Screenshot 2020-09-28 at 19 08 16" src="https://user-images.githubusercontent.com/296665/94463927-fcffc780-01bd-11eb-803a-9c6f15cac0df.png">

We shouldn't see the directory in this scenario, because there's no actual directory, we're looking at a single file. So either:
- Go up to the parent directory when clicking "close" button
- Or hide the "close" button

**Comment by matheus23** [comment]
Alternatively, go back to the directory when hitting close?

**Comment by icidasset** [comment]
By going up to the directory automatically? Yeah that could work as well 👍
