### ISSUE TITLE
Code Structure: Making impossible states unrepresentable, Drive.Sidebar edition

### ISSUE THREAD

**Issue by matheus23** [fission-suite/drive#83]
I'd like to organize some thoughts around the state structure of the sidebar, both because writing it out makes it clear for myself, and for input from @icidasset. I'd argue this is a preferable, small refactor, what do you think?

# The issue

At the moment there's some invariants between some fields of `Model`:

* `showPreviewOverlay` is false if `selectedPath` is Nothing. It being true would be an 'impossible state'.
* `createDirectoryInput` has some value even if `selectedPath` is Nothing.
* `sidebarMode` is always `Drive.Sidebar.defaultMode` if `selectedPath` is Nothing.
* `expandSidebar` is always false if `selectedPath` is Nothing.

This means that, to get desired behavior when closing/reopening the sidebar, we have to make sure not to forget to reset these values to the default.

When I added another mode to `sidebarMode` this caused my code to not correctly close the sidebar. I think this resetting code doesn't have to exist.

# The solution

Put the state that has a dependency on `selectedPath` 'inside the custom type'. Perhaps something like this:

```diff
type alias Model =
    { ...
-    , selectedPath : Maybe String
    ...
    -----------------------------------------
    -- Sidebar
    -----------------------------------------
-    , createDirectoryInput : String
-    , expandSidebar : Bool
-    , showPreviewOverlay : Bool
-    , sidebarMode : Drive.Sidebar.Mode
    , selected : Maybe { path : String, sidebar : Drive.Sidebar.Model }
    }

+selectedPath : Model -> Maybe String
+selectedPath model =
+    model.sidebar |> Maybe.map .path
```

```elm
-- in Drive.Sidebar
type alias Model =
    { expand : Bool
    , mode : Mode
    }

type Mode
    = AddOrCreate { input : String }
    | Details { showPreviewOverlay : Bool }
```

For #82 I'd then add another case to `Mode`:
```elm
type Mode
    = AddOrCreate { input : String }
    | Details { showPreviewOverlay : Bool }
    | PlaintextEditor
        { text : String
        , originalText : String -- for figuring out whether we have to save
        }
```

The benefit of this is that e.g. something like closing the sidebar becomes much simpler, as it can simply set `selected = Nothing`.
On a more general level, it is less likely to introduce code that leaves the UI in an undesired state.

**Comment by matheus23** [comment]
I have to think about this a little more.

There are two types of sidebars: One for the `AddOrCreate` sidebar, and one for the details sidebar.
The details sidebar can only be opened, when the `selectedPath` is not Nothing.
The add or created sidebar can be open at any time. Even 'on top' of a details sidebar.

These states wouldn't be representable with my current proposal.
I still think a slightly modified design is preferable, but I'll have to go back to the drawing board.

**Comment by icidasset** [comment]
Thanks! Yeah this definitely needs a refactor. Also something to consider is that soon `selectedPath` will become `selectedPaths`, since you'll be able to select multiple files/dirs. Not sure I'd combine the selected paths with the sidebar, but I agree with putting the state on the Mode type and having a Sidebar Model type 👍 

> The add or created sidebar can be open at any time. Even 'on top' of a details sidebar.

Did I make that possible? 🤔 😅 
I would think that it's only one or the other (ie. either add-create or details)

**Comment by matheus23** [comment]
> I would think that it's only one or the other (ie. either add-create or details)

The way the code is concerned, yes. But from the view of a user, you can open a details pane, then an add/create pane, and when you close that you come back to a details pane.

**Comment by matheus23** [comment]
This is now in a PR.
Radix.elm, the Model type:
```diff
    -----------------------------------------
    -- Sidebar
    -----------------------------------------
-    , createDirectoryInput : String
-    , expandSidebar : Bool
-    , showPreviewOverlay : Bool
-    , sidebarMode : Drive.Sidebar.Mode
+    , sidebar : Maybe Drive.Sidebar.Model
+    , addOrCreate : Maybe Drive.Sidebar.AddOrCreateModel
    }
```

And in the Drive.Sidebar module:
```elm

type alias Model =
    { expanded : Bool
    , path : String
    , mode : Mode
    }


type Mode
    = Details { showPreviewOverlay : Bool }
    | EditPlaintext EditorModel


type alias EditorModel =
    { text : String
    , originalText : String
    }


type alias AddOrCreateModel =
    { expanded : Bool
    , input : String
    }
```

I guess we can close this :+1:
