### ISSUE TITLE
Code Structure: Removing loadingDebouncer

### ISSUE THREAD

**Issue by matheus23** [fission-suite/drive#87]
During refactoring I've come accross `model.loadingDebouncer : Debouncer Msg`.

It was added in #53 

I'm not sure what it does. It seems to only be set, never read.

Can/should we remove that @icidasset ?

**Comment by icidasset** [comment]
Hmm, I feel like we still need that, but not sure. If I recall correctly, it was to show a loading indicator when navigating through your file system, but only if the action took too long. So for example, I would go up a directory via the breadcrumbs navigation, and that action takes over 5 seconds, then I'd show a loading indicator.

It may have been lost when refactoring 🤷 😅

**Comment by icidasset** [comment]
Used in `Drive.State.goUp`, see `Debouncing.loading.provideInput`.

**Comment by matheus23** [comment]
Whoops. Seems like my codebase-search-foo has been failing me. :smile:
