### ISSUE TITLE
Initialize empty files from within drive

### ISSUE THREAD

**Issue by matheus23** [fission-suite/drive#91]
Some things to consider:
* What types of files do we want to support? Potential answer: All file types recognized as Text/Code
* Where do we initialize files? Probably in the same dialog as the 'add directory'

Other than that it should be straight-forward.

**Comment by matheus23** [comment]
I've been thinking about how to design this feature.

Here are some in-context mockups for creating files:

![Add Dialog Option 1](https://user-images.githubusercontent.com/1430958/98933743-58bdb000-24e1-11eb-865e-4e85260224ea.png)
([In Figma](https://www.figma.com/proto/wqJjBsfSAIWzwPsLdMkl1t/Fission?node-id=228%3A1171&scaling=min-zoom))

![Add Dialog Option 2](https://user-images.githubusercontent.com/1430958/98934085-d1247100-24e1-11eb-958f-edff23ab80fd.png)
([In Figma](https://www.figma.com/proto/wqJjBsfSAIWzwPsLdMkl1t/Fission?node-id=228%3A1010&scaling=min-zoom))

Ignore the styling for now.
Conceptually, it's possible to create empty files of any type in the first option, but it's not immediately obvious which files would work well for fission drive. With the second option it's possible to give users a nudge in the 'successful' direction: Adding files that drive supports.

At the moment, these are the file endings that fission recognizes:
https://github.com/fission-suite/drive/blob/e857fa07c35fdc9846ff3259ae3a9d1ff2708184/src/Application/Drive/Item.elm#L53-L70

---

I'm not happy with either, but I think creating option 1 quickly would be easy and the low-hanging fruit. Otherwise I hope someone chimes in with an idea of their own :sweat_smile:

**Comment by bmann** [comment]
I actually think Option 2 is “easier” because it helps illustrate what is possible. There’s one less “don’t make me think” — you choose if you want a text file, markdown, or HTML. 

Also: could rename files afterwards to change file extension. 

Also realizing how much naming consistency we have to work on. We’re vaguely following MacOS guidance. We should say “Folder” rather than directory. And it should say “New Folder” and If you don’t type anything it’s just called new folder. 

Each of the file types — probably all `untitled.EXT`

There’s likely a whole other UX to do this that is around icons in the file listing itself — a folder with a + icon, a file with a + icon, and then it puts in a new entry at the bottom where you are in rename mode over top of “New Folder” or “untitled.txt”. But that means doing ACTUAL design work on the whole app!

Does that make sense?

**Comment by matheus23** [comment]
> There’s likely a whole other UX to do this that is around icons in the file listing itself — a folder with a + icon, a file with a + icon, and then it puts in a new entry at the bottom where you are in rename mode over top of “New Folder” or “untitled.txt”. But that means doing ACTUAL design work on the whole app!

Would love to do that. Makes me think that it'd be possible to incorporate all of the functionality from the add/create dialog into the app, making it redundant. (although that'd lose the 'illustrate what's possible' thing)

> Also realizing how much naming consistency we have to work on. We’re vaguely following MacOS guidance. We should say “Folder” rather than directory. And it should say “New Folder” and If you don’t type anything it’s just called new folder.

Totally agree. I also think 'Folder' is just a better term than 'directory'.

---

![AddOrCreateDialog](https://user-images.githubusercontent.com/1430958/99377872-0a385900-28c7-11eb-9b6b-9530ff33d2cc.png)

Finally just going with this design. I think ux-wise it's quite clear what should happen. The design of the buttons can be adjusted later. For now I'm rolling with smaller buttons, because we don't have very indicative icons for the different filetypes.

**Comment by icidasset** [comment]
I like that @matheus23 👏 
Don't think it's very responsive though.
Could we do one folder button and one file button with dropdown arrow in it? 🤔 
Clicking on the dropdown would show other options.

Or we could stick with this for now, and I can adjust later, that's fine too.

**Comment by matheus23** [comment]
On smaller screens the button row wraps around like this:
![image](https://user-images.githubusercontent.com/1430958/99509937-bb51f880-2986-11eb-94f0-e19105fbeb40.png)
I agree it doesn't look very nice on mobile screens
![image](https://user-images.githubusercontent.com/1430958/99510084-e8061000-2986-11eb-8855-8d9ca2e02e53.png)

These are images of the implementation, so I've started already. I think I'll go with it for now.

I have some ideas how it would work if I were thinking about this more thoroughly.
I think I'll mock up some of these ideas in figma and post them here just to have them persisted, but for now I'll implement just the buttons.

**Comment by matheus23** [comment]
>  I think I'll mock up some of these ideas in figma and post them here just to have them persisted, but for now I'll implement just the buttons.

I quickly did that, but didn't show you, yet. Here's a prototype of what I was thinking of:
https://www.figma.com/proto/yOwxZsqxyiGyu4A9UHd0EE/Fission?node-id=265%3A1405&scaling=min-zoom

I really like this kind of flow which is similar to how it works in other file browsers.

Some downsides to this are:
* It's 3 more buttons to show and as a result, it's slightly less uncluttered.
  - I did think about this being a right click action on empty space, like in other file browsers, but that's bad UX for mobile and generally I really dislike this UX pattern as it makes this feature hardly discoverable.
  - I would argue that these three actions are central to a file browser and therefore justify the cluttering.
* You lose that "it helps illustrate what is possible" in the sense of you just choose "HTML", "TXT" or "MD".

Let me know what you think!

In any case, this is just mindstorming for a possible V2. V1 is already implemented and in the process of polishing.

**Comment by icidasset** [comment]
I don't want to add any more things there. Plus, what if you have a large list of files?
We should change the action space in the bottom right corner instead.
We can easily replace the "Add / Create" with your suggested actions.

I do like the "in tree" file renaming, which I planned to do, but opted for a modal instead.
I'm not sure we need the complexity of that UI, as opposed to a modal.
And a modal you can trigger from elsewhere as well.
But I do like the familiarity of the "in tree" renaming.
Thoughts?

**Comment by matheus23** [comment]
>  We can easily replace the "Add / Create" with your suggested actions.

Yep that sounds good if we're ok with removing the add/create sidebar and the "illustrate what's possible" downside.

> Plus, what if you have a large list of files?

Good point. A large list would mean either the icons should be scroll-fixed (they would be if they're in the footer) or they'd scroll out of view. I think that's another point in favor of putting that in the footer.

I do like the "in tree" file renaming, which I planned to do, but opted for a modal instead.
> I'm not sure we need the complexity of that UI, as opposed to a modal.
And a modal you can trigger from elsewhere as well.
But I do like the familiarity of the "in tree" renaming.
Thoughts?

How about going with the patterns we already have (modals) and reusing them little more: Putting "New Folder" and "New File" into the footer instead of the "Add/Create" toggle. These would just open a modal.
Benefits of a modal are:
* They're easier to implement at the moment
* They can be more complex than in-tree renaming (Suggesting different file endings would be possible)
* You can provide a 'cancel' action visually

Anyway, I guess this is just mindstorming at this point without an actual plan for an overhaul. It was just something I had been thinking about and wanted to write down and discuss a little. Thanks!
