### ISSUE TITLE
.pdf and .doc files shouldn't be openable with the plaintext editor

### ISSUE THREAD

**Issue by matheus23** [fission-suite/drive#92]
At the moment, they're categorized as the `Text` file type in the codebase:
https://github.com/fission-suite/drive/blob/e857fa07c35fdc9846ff3259ae3a9d1ff2708184/src/Application/Drive/Item.elm#L53-L70

Possible solution: Introduce a file type `RichText`.

**Comment by icidasset** [comment]
I agree with `RichText` 👍
