### ISSUE TITLE
Should not be able to move a file through renaming

### ISSUE THREAD

**Issue by icidasset** [fission-suite/drive#97]
The renaming functionality uses `mv` underneath, so if you rename a file to `example/file.txt`, you'll create the example directory. I'm not entirely sure, but I think we should avoid this. Otherwise people'd expect to, for example, `../file.txt` to work as well, which does not work.

The UI I have in mind for this scenario is:
1. Create a new directory as usual
2. Drag and drop the file into the new directory

**Comment by matheus23** [comment]
Drag and drop is mentioned in #45 

Would love this feature! But drag and drop is hard :(

**Comment by bmann** [comment]
We talked about this internally, best to leave a public comment ;)

Implement a rename filter that changes non-allowed characters into “-“.

Technically with how we do metadata, any file name could be allowed as the title I think, but that’s a different issue. 

Could specifically have a convenience “rename” function that implements the filter and calls “mv” underneath.
